export const GET_LIST_ARTICLES = '@HOME/GET_LIST_ARTICLES'
export const GET_LIST_ARTICLES_SUCCESS = '@HOME/GET_LIST_ARTICLES_SUCCESS'
export const GET_LIST_ARTICLES_ERROR = '@HOME/GET_LIST_ARTICLES_ERROR'

export const GET_DETAIL_ARTICLES = '@HOME/GET_DETAIL_ARTICLES'
export const GET_DETAIL_ARTICLES_SUCCESS = '@HOME/GET_DETAIL_ARTICLES_SUCCESS'
export const GET_DETAIL_ARTICLES_ERROR = '@HOME/GET_DETAIL_ARTICLES_ERROR'

export const UPDATE_ARTICLES = '@HOME/UPDATE_ARTICLES'
export const UPDATE_ARTICLES_SUCCESS = '@HOME/UPDATE_ARTICLES_SUCCESS'
export const UPDATE_ARTICLES_ERROR = '@HOME/UPDATE_ARTICLES_ERROR'

export const CREATE_ARTICLES = '@HOME/CREATE_ARTICLES'
export const CREATE_ARTICLES_SUCCESS = '@HOME/CREATE_ARTICLES_SUCCESS'
export const CREATE_ARTICLES_ERROR = '@HOME/CREATE_ARTICLES_ERROR'
